### ISSUE TITLE
Logs are discarded when stdout is a pipe

### ISSUE THREAD

**Issue by filterfish** [ocharles/logging-effect#14]
I'm using [nosh](http://jdebp.eu/Softwares/nosh/) (a daemontools derivative) as a process supervisor and stdout is piped to a logging process. This causes all logs to be discarded.

As a simple test I simply piped my program through `cat` and logs are, again, discarded. Being a pedant I even double checked with `strace`! When stdout is a tty I see: `write(1, "...") ...` but when stdout is a pipe nothing is written to file descriptor 1.

I can understand interactive programs discarding output when stdout is a pipe but surely not a logging library!

**Comment by ocharles** [comment]
Could you provide me with a minimal example to reproduce this problem?

**Comment by filterfish** [comment]
Yeah, I will do. I'm still trying to work out what's actually going on; sometimes it works and others not. I'll try and get an example together soon.

**Comment by filterfish** [comment]
Ok, I created a [repo](github.com/filterfish/logging-effect-test) and have written up what I think is going on in the [README](github.com/filterfish/logging-effect-test/blob/master/README.md). 

In short I don't think this is a bug but an interaction with stdout buffering. I'm not sure what the best answer is but it might be worth at least documenting that this can happen.

I was thinking that the library could set stdout and stderr's buffer options to `LineBuffering` but that goes against the grain of what batching is doing. Maybe it should be set when not using the batching (I haven't tested whether this shows the same behaviour).

**Comment by ocharles** [comment]
Richard Heycock <notifications@github.com> writes:

> Ok, I created a [repo](github.com/filterfish/logging-effect-test) and have written up what I think is going on in the [README](github.com/filterfish/logging-effect-test/blob/master/README.md). 
>
> In short I don't think this is a bug but an interaction with stdout buffering. I'm not sure what the best answer is but it might be worth at least documenting that this can happen.
>
> I was thinking that the library could set stdout and stderr's buffer
> options to `LineBuffering` but that goes against the grain of what
> batching is doing. Maybe it should be set when not using the batching
> (I haven't tested whether this shows the same behaviour). 

I don't think it should change how buffering happens, but it sounds like
it just needs to explicitly flush the handle when writing.
I'll add that in!

**Comment by ocharles** [comment]
@filterfish I have pushed what I think is a fix for this problem to the `master` branch - could you try that and see if it does indeed fix the problem?

**Comment by filterfish** [comment]
Works like a charm! Thanks for fixing it.

**Comment by ocharles** [comment]
Wonderful, I've now released that as 1.2.0 on Hackage. It's a major bump as this is an observable change.
