### ISSUE TITLE
Error in doc for `renderWithSeverity`

### ISSUE THREAD

**Issue by tekul** [ocharles/logging-effect#2]
The description seems to be wrong and also the code example looks like it's from an earlier incarnation of the API. Seems like it should be:

```
renderWithSeverity id (WithSeverity Informational "Flux capacitor is functional")
```

rather than

```
renderWithSeverity id Debug (WithSeverity Info "Flux capacitor is functional")
```

**Comment by ocharles** [comment]
Thanks for spotting this! I've updated the documentation and re-uploaded it to Hackage.
