### ISSUE TITLE
Q: logging over PrimMonad

### ISSUE THREAD

**Issue by ocramz** [ocharles/logging-effect#20]
I have an action that typechecks as 

```
create >>= sample t
  :: (MonadLog (WithSeverity String) m, PrimMonad m) => m Double
```

Internally, it produces random numbers, which yields the PrimMonad constraint.
I can't seem to figure out a way to execute this composite effect, so any help would be appreciated. Thanks!

**Comment by ocramz** [comment]
Tired eyes produce bad code; refactoring bypassed this problem. Thanks anyway!

**Comment by ocharles** [comment]
Glad you found a solution!
