### ISSUE TITLE
Support GHC 8.4 and re-add to Stackage

### ISSUE THREAD

**Issue by ocramz** [ocharles/logging-effect#22]

**Comment by ocharles** [comment]
`logging-effect` has been in Stackage for quite a while - https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L1897. I think I'm missing something though, is something not working? I'll re-open this once we work out if there is still something I need to fix.

**Comment by ocramz** [comment]
Apologies for the wrong title; the problem seems to be that logging effect doesn't build with GHC 8.4.1 , as the stackage editors wrote in `constraints.yaml` : ` - logging-effect < 0 # GHC 8.4 via base-4.11.0.0`

**Comment by ocharles** [comment]
Aha, thanks! I'll get on that.

**Comment by ocharles** [comment]
It looks like we're back in Stackage. Please let me know if that is not the case.
