### ISSUE TITLE
Split out logging-effect-light ?

### ISSUE THREAD

**Issue by ocramz** [ocharles/logging-effect#23]
Would you accept a PR that splits out the basic functionality of the library as a separate package, and reimports that as a dependency to `logging-effect`?

I was thinking for example of isolating the parts of the library that don't require `free`, which carries a comparatively large transitive dependency tree.

**Comment by ocharles** [comment]
I'd be more inclined to drop `free`. There would be no way to write `logging-effect` that depends on `logging-effect-light` to provide the `MonadFree` instance without orphan instances. Is the dependency graph really problematic though? `free` is a pretty central dependency these days and gets a lot of attention for build plans.

**Comment by ocramz** [comment]
Good point on the orphan MonadFree instance; this invalidates my proposal in fact. 

I agree that `free` is quite common but it seems to me that a large portion of the cold-start build time of logging-effect is due to free and friends.
