### ISSUE TITLE
RFC: Switch from wl-pprint-text to prettyprinter

### ISSUE THREAD

**Issue by cocreature** [ocharles/logging-effect#24]
`prettyprinter` is a fairly recent but (in my experience) very solid library that aims to consolidate the various libraries for prettyprinting that we have in the Haskell ecosystem. I’ll leave it to the [README](https://github.com/quchen/prettyprinter#why-another-prettyprinter) to give a detailed comparison.

I’ve been switching most of my projects over to `prettyprinter` but `logging-effect` is one of the packages that still uses `wl-pprint-text`. Would you be open to switching to `prettyprinter`? I’d be happy to try and provide a PR in that case. Ofc I also realize that you probably have quite a bit of code that relies on `logging-effect` and given that this would be a breaking change I can completely understand if you’re not too keen on switching :)

**Comment by ocharles** [comment]
I'm a big fan of prettyprinter. Definitely open to this.

**Comment by ocharles** [comment]
Done!
