### ISSUE TITLE
add module with short names to log with severity

### ISSUE THREAD

**Issue by ibotty** [ocharles/logging-effect#4]
Maybe something to be imported qualified. E.g.

```
import Control.Monad.Log.LogMessage as Log

f = do
    Log.debug "debug message"
    Log.errror "error message"
```

What do you think?

**Comment by ocharles** [comment]
1.1.0 will have the following: https://github.com/ocharles/logging-effect/blob/b83c7a1e2ef08cc124d9bb10db6e6aa98cba0e34/src/Control/Monad/Log.hs#L43 (https://github.com/ocharles/logging-effect/blob/b83c7a1e2ef08cc124d9bb10db6e6aa98cba0e34/src/Control/Monad/Log.hs#L209)

Would they be sufficient?

**Comment by ibotty** [comment]
I was just about to comment on that. Yes, they are sufficient. I prefer a separate module to be imported qualified, but I am fine either way. Is there an ETA?

**Comment by ibotty** [comment]
BTW: now, that you are here: What do you think about an extensible exception-like thing for Log messages. I could (and do) roll my own sum type for typed log messages pretty often, but having an extensible framework in place would be great. `Doc` is not so great for structured logging.

**Comment by ocharles** [comment]
ETA is within the next 2 weeks at most, but hopefully this week.

`Doc` is only for when you want to log to something that is unstructured - if you have a sink that supports more structure then the idea is to build your own batched handler and work with whatever message type you like. There are so many options here I'm not sure what an extensible framework would look like. Happy to chat about that, if you want to open another issue with what you have in mind.

**Comment by ocharles** [comment]
So much for two weeks, but now released!
